language: node_js
node_js: lts/*
jobs:
  include:
    - stage: DEPLOY
      script: './deploy.sh'
      deploy:
        app: photon-knowledge-junction
        api_key: 8ff7acb1-866d-46ba-8869-9be6a99e6fa8
        provider: heroku
        run: restart
        skip_cleanup: true